# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e403107eca9c026c0f44d9132d036058"
name = "inventory-app"
handle = "inventory-app-60"
application_url = "https://feel-harassment-lanka-documentation.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-a69d9366.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://feel-harassment-lanka-documentation.trycloudflare.com/auth/callback",
  "https://feel-harassment-lanka-documentation.trycloudflare.com/auth/shopify/callback",
  "https://feel-harassment-lanka-documentation.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
